version: 2
updates:
  - package-ecosystem: "pip"
    directory: "ncmma"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "docker"
    directory: "ncmma"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
